name: Build Cross-Platform Binaries

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            python-arch: x64
          - os: linux  
            arch: arm64
            runner: ubuntu-latest
            python-arch: x64  # Cross-compile

          # macOS builds
          - os: macos
            arch: x86_64
            runner: macos-13  # Intel runner
            python-arch: x64
          - os: macos
            arch: arm64
            runner: macos-14  # Apple Silicon runner
            python-arch: arm64

          # Windows builds
          - os: windows
            arch: x86_64
            runner: windows-latest
            python-arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: ${{ matrix.python-arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build binary
        run: python build.py

      - name: Test binary
        run: python build.py --test

      - name: Create release artifact
        run: |
          mkdir -p release
          # Copy both binaries
          if [ "${{ matrix.os }}" = "windows" ]; then
            cp binaries/wakaterm-${{ matrix.os }}-${{ matrix.arch }}.exe release/ 2>/dev/null || true
            cp binaries/wakatermctl-${{ matrix.os }}-${{ matrix.arch }}.exe release/ 2>/dev/null || true
            # Also copy distribution directories
            cp -r binaries/wakaterm-dist release/ 2>/dev/null || true
            cp -r binaries/wakatermctl-dist release/ 2>/dev/null || true
          else
            cp binaries/wakaterm-${{ matrix.os }}-${{ matrix.arch }} release/ 2>/dev/null || true
            cp binaries/wakatermctl-${{ matrix.os }}-${{ matrix.arch }} release/ 2>/dev/null || true
            # Also copy distribution directories
            cp -r binaries/wakaterm-dist release/ 2>/dev/null || true  
            cp -r binaries/wakatermctl-dist release/ 2>/dev/null || true
          fi
          cp README.md LICENSE release/
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wakaterm-${{ matrix.os }}-${{ matrix.arch }}
          path: release/
          retention-days: 90

  release:
    name: Attach Files to Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release archive
        run: |
          mkdir -p release
          cd artifacts
          for dir in */; do
            if [ -d "$dir" ]; then
              cd "$dir"
              if ls wakaterm*.exe 1> /dev/null 2>&1; then
                # Windows binary
                zip -r "../../release/${dir%/}.zip" *
              else
                # Unix binary  
                tar -czf "../../release/${dir%/}.tar.gz" *
              fi
              cd ..
            fi
          done

      - name: Attach Files to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the release tag
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "Attaching files to release: $TAG_NAME"
          
          # Upload all release files to the existing release
          for file in release/*; do
            if [ -f "$file" ]; then
              echo "Uploading: $file"
              gh release upload "$TAG_NAME" "$file" --clobber
            fi
          done